import turtle

hamza_turtle = turtle.Turtle()
def turt():
    hamza_turtle.forward(200)
    hamza_turtle.right(90)
    hamza_turtle.forward(200)
    hamza_turtle.right(90)
    hamza_turtle.forward(200)
    hamza_turtle.right(90)
    hamza_turtle.forward(200)
    hamza_turtle.left(50)
    hamza_turtle.forward(200)
    hamza_turtle.left(130)
    hamza_turtle.forward(200)
    hamza_turtle.left(90)
    hamza_turtle.forward(200)
    hamza_turtle.right(40)
    hamza_turtle.forward(200)
    hamza_turtle.left(130)
    hamza_turtle.forward(200)
    hamza_turtle.left(50)
    hamza_turtle.forward(200)
    hamza_turtle.left(40)
    hamza_turtle.forward(200)
    hamza_turtle.left(90)
    hamza_turtle.forward(200)
    hamza_turtle.left(50)
    hamza_turtle.forward(200)
    hamza_turtle.left(110)
    hamza_turtle.forward(139)
    hamza_turtle.left(20)
    hamza_turtle.forward(200)
i = 0
for i in range(2):
    turt()
